Add prediction service to both clusters
digicatapult/bridgeAI-gitops-infra pull request #22
Opened 2024-10-21 15:12 UTC by elisehaldane

# Pull Request

## Checklist
- [x] Have you read Digital Catapult's [Code of Conduct](https://github.com/digicatapult/.github/blob/main/CODE_OF_CONDUCT.md)?
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## PR Type

Please delete options that are irrelevant.

- [x] Feature

## Linked tickets

[BRID-108](https://digicatapult.atlassian.net/browse/BRID-108)

## High level description

This PR is to add the BridgeAI prediction service to both clusters (via our own helm chart), with a view to making it accessible at [predict.dc-mlops.co.uk](https://predict.dc-mlops.co.uk).

[BRID-108]: https://digicatapult.atlassian.net/browse/BRID-108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-22 12:51 UTC, dblane-digicatapult requested changes

2024-10-22 12:54 UTC, elisehaldane commented on flux/clusters/bridgeai-prod/prediction-service/account.yaml
> +  namespace: prediction-service
It wasn't being created. I'm still debugging.

2024-10-22 12:58 UTC, dblane-digicatapult commented on flux/clusters/bridgeai-prod/prediction-service/account.yaml
> +  namespace: prediction-service
Remove this for now and lets debug this bit later on.

2024-10-25 09:11 UTC, dblane-digicatapult submitted a review, later dismissed

2024-10-25 09:15 UTC, dblane-digicatapult approved these changes

2024-10-25 09:17 UTC, merged